name: Validate AI Workflow JSONs

on:
  pull_request:
    paths:
      - 'models/**.json'
      - 'examples/**.json'
      - 'schemas/**.json'

jobs:
  validate-json:
    runs-on: ubuntu-latest

    steps:
      # Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install jsonschema

      # Run JSON validation script
      - name: Validate JSON files
        run: |
          python scripts/validate_json.py

